=== dneukirchen/joomla-pythagoras/libraries/incubator/ORM/Definition/entity.dtd
<!ELEMENT entity (storage, (fields)?, (relations)?)>
    <!ATTLIST entity
        name CDATA #REQUIRED
        extends CDATA #IMPLIED>

    <!ELEMENT storage (default|api|special)>

    <!ELEMENT default EMPTY>
    <!ATTLIST default
        table NMTOKEN #REQUIRED
        primary CDATA #IMPLIED>

    <!ELEMENT api EMPTY>
    <!ATTLIST api
        base-url CDATA #IMPLIED
        handler CDATA #REQUIRED
        primary CDATA #IMPLIED>

    <!ELEMENT special EMPTY>
    <!ATTLIST special
        dsn CDATA #REQUIRED
        primary CDATA #IMPLIED>

    <!ELEMENT fields (field|fieldset)+>

    <!ELEMENT fieldset (field)+>
    <!ATTLIST fieldset
        description CDATA #IMPLIED
        label CDATA #IMPLIED
        name ID #REQUIRED
        filter CDATA #IMPLIED
        required (true|false) "false"
        type NMTOKEN #REQUIRED>

    <!ELEMENT field (validation|option)*>
    <!ATTLIST field
        default CDATA #IMPLIED
        description CDATA #IMPLIED
        label CDATA #IMPLIED
        hint CDATA #IMPLIED
        name ID #REQUIRED
        filter CDATA #IMPLIED
        required (true|false) "false"
        type NMTOKEN #REQUIRED>

    <!ELEMENT validation EMPTY>
    <!ATTLIST validation
        rule NMTOKEN #REQUIRED
        value CDATA #IMPLIED>

    <!ELEMENT option (#PCDATA)>
    <!ATTLIST option
        value CDATA #IMPLIED>

    <!ELEMENT relations (belongsTo|hasOne|hasMany|hasManyThrough)+>

    <!ELEMENT belongsTo EMPTY>
    <!ATTLIST belongsTo
        name ID #REQUIRED
        entity NMTOKEN #REQUIRED
        label CDATA #IMPLIED
        description CDATA #IMPLIED
        default CDATA #IMPLIED>

    <!ELEMENT hasOne EMPTY>
    <!ATTLIST hasOne
        name ID #REQUIRED
        entity NMTOKEN #REQUIRED
        reference NMTOKEN #REQUIRED
        label CDATA #IMPLIED
        description CDATA #IMPLIED
        default CDATA #IMPLIED>

    <!ELEMENT hasMany EMPTY>
    <!ATTLIST hasMany
        name ID #REQUIRED
        entity NMTOKEN #REQUIRED
        reference NMTOKEN #REQUIRED
        label CDATA #IMPLIED
        description CDATA #IMPLIED
        default CDATA #IMPLIED>

    <!ELEMENT hasManyThrough EMPTY>
    <!ATTLIST hasManyThrough
        name ID #REQUIRED
        entity NMTOKEN #REQUIRED
        reference NMTOKEN #REQUIRED
        joinTable NMTOKEN #REQUIRED
        joinRef NMTOKEN #REQUIRED
        label CDATA #IMPLIED
        description CDATA #IMPLIED
        default CDATA #IMPLIED>

=== dneukirchen/joomla-pythagoras/libraries/incubator/PageBuilder/entities/Page.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE entity SYSTEM
    "https://github.com/nibralab/joomla-architecture/blob/master/code/Joomla/ORM/Definition/entity.dtd">
<entity name="Joomla\PageBuilder\Entity\Page">

    <storage>
        <default table="pages"/>
    </storage>

    <fields>
        <field name="id"
               type="id"
               label="JGLOBAL_FIELD_ID_LABEL"
               description="JGLOBAL_FIELD_ID_DESC"
               default="null"
        >
            <validation rule="positive"/>
            <validation rule="integer"/>
        </field>

        <field name="title"
               type="title"
               label="JGLOBAL_TITLE"
        >
            <validation rule="maxlen" value="64"/>
        </field>

        <field name="url" type="url"/>

    </fields>

    <relations>
        <belongsTo name="parent_id"
                   entity="Page"
                   label="JFIELD_PARENT_LABEL"
                   description="JFIELD_PARENT_DESC"
        />
        <belongsTo name="layout_id" entity="Layout"/>
        <hasMany name="children" entity="Page" reference="parent_id"/>
        <hasMany name="content" entity="Content" reference="page_id"/>
    </relations>

</entity>

=== dneukirchen/joomla-pythagoras/libraries/incubator/PageBuilder/entities/Layout.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE entity SYSTEM
    "https://github.com/nibralab/joomla-architecture/blob/master/code/Joomla/ORM/Definition/entity.dtd">
<entity name="Joomla\PageBuilder\Entity\Layout">

    <storage>
        <default table="layouts"/>
    </storage>

    <fields>
        <field name="id"
               type="id"
               label="JGLOBAL_FIELD_ID_LABEL"
               description="JGLOBAL_FIELD_ID_DESC"
               default="null"
        >
            <validation rule="positive"/>
            <validation rule="integer"/>
        </field>

        <field name="title"
               type="title"
               label="JGLOBAL_TITLE"
        >
            <validation rule="maxlen" value="64"/>
        </field>

    </fields>

    <relations>
        <belongsTo name="parent_id"
                   entity="Layout"
                   label="JFIELD_PARENT_LABEL"
                   description="JFIELD_PARENT_DESC"
        />
        <belongsTo name="template_id"
                   entity="Template"
        />
        <hasMany name="children" entity="Layout" reference="parent_id"/>
        <hasMany name="pages" entity="Page" reference="layout_id"/>
        <hasMany name="content" entity="Content" reference="layout_id"/>
    </relations>

</entity>
